/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Convert JavaScript source code into a WebAssembly component.
 *
 * Takes a WIT definition and JavaScript source, compiles them into a
 * WebAssembly component using the QuickJS runtime.
 */
export declare function componentize(opts: ComponentizeOpts): Promise<ComponentizeResult>

/** Options for componentizing a JavaScript source into a WebAssembly component. */
export interface ComponentizeOpts {
  /** Path to the WIT file or directory */
  witPath: string
  /** JavaScript source code */
  jsSource: string
  /** World name to use from the WIT (omit for default world) */
  world?: string
  /** Stub all WASI imports with traps (default: false) */
  stubWasi?: boolean
}

/** Result of componentizing a JavaScript source. */
export interface ComponentizeResult {
  /** The WebAssembly component bytes */
  component: Buffer
}

/**
 * NAPI CLI entry point.
 *
 * Returns `true` if the command succeeded, `false` otherwise.
 */
export declare function runCli(args: Array<string>): Promise<boolean>
